//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace app.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class thucUong
    {
        public int maThucUong { get; set; }
        public string tenThucUong { get; set; }
        public Nullable<double> giaBan { get; set; }
        public string nguyenLieu { get; set; }
        public byte[] anhThucUong { get; set; }
    }
}
